server:
  port: 7600
spring:
  application:
    name: demo

  r2dbc:
    username: ${database.username}
    password: ${database.password}
    url: r2dbc:mysql://${database.url}/${database.name}?useUnicode=true&tlsVersion=TLSv1.2&characterEncoding=utf-8&useSSL=false&autoReconnect=true&failOverReadOnly=false&serverTimezone=Asia/Shanghai

#  liquibase:
#    enabled: true
#    url: jdbc:mysql://${database.url}/${database.name}
#    user: ${database.username}
#    password: ${database.password}
#    change-log: classpath:db/changelog/changelog.yaml


  data:
    redis:
      repositories:
        enabled: false
      host: 127.0.0.1
      port: 31514
      database: 0
      timeout: 10s
#logging:
#  level:
#    org:
#      springframework:
#        r2dbc: debug
database:
  name: shore
  username: root
  password: password
  url: 127.0.0.1:30306

shore:
  security:
    cache: redis
  logging:
    loki:
      enabled: true
      http-url: https://loki.rime.sh/loki/api/v1/push
      http-tenant-id: xxxx
  exception:
    enable: false
  rabbitmq:
    host: 127.0.0.1
    port: 31688
    username: guest
    password: guest
    virtual-host: /

management:
  endpoints:
    web:
      exposure:
        include: '*'
        